import React from "react";
import Navbar from "./components/nav/Navbar";
import "./css/globals.css";
import { ReactNode } from "react";

export const metadata = {
  title: "COSCI-CONNECT",
  description: "Generated by create next app",
};

interface RootLayoutProps {
  children: ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body>
        <Navbar />
        <div className="py-20 px-4 md:px-4 lg:px-4 xl:px-12">
          {children}
        </div>
      </body>
    </html>
  );
}